[build]
  command = "npm run build"
  publish = "dist"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to Azure backend  
[[redirects]]
  from = "/api/*"
  to = "https://scout-analytics-api.azurewebsites.net/api/:splat"
  status = 200
  force = true